apiVersion: v1
kind: Secret
metadata:
    name: ror-poc
    namespace: ror-poc
data:
    secret_key_base: ENC[AES256_GCM,data:pqJwm2pu4YjKL+dTWq0UN5K3SwOHXg0caG+X7scrDElW7pXAdkV2qK/SzCdfaGhHGC2JwDlS8Yu5bQXHLrX1Fg==,iv:PJnzUzv5WQoyL3edNjNBxOi1Y974Mv2r/Oufk3ISdqM=,tag:04pJSXsCz35NCB+j2jGlJQ==,type:str]
    postgres_password: ENC[AES256_GCM,data:c9C3Vrg5n18TFzVl,iv:Nq+YNyFZZ+XDF80UBXCQ8SdbhxMSTgKt4Vgyir8KPRs=,tag:sDzF14i0Rj84+shvkRP5AA==,type:str]
sops:
    age:
        - recipient: age14elm7mh8cvjujj5wtzl74ykqka5n82f569xl8284ajmv57424urslyyljz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHbXFEZ3MwWTJVd1grSEVp
            MkJNQ05TU0hraVF3STVpVG1OS0ZIbnUwcVhJCnFLWmNueE9YbkdhMmgwYXhiNU41
            L1YwMUJWYmNjOEZpRHYzYkNEV1lCWWsKLS0tIDVhYXR4VkdlekhiZ1VURjBWcWlN
            RnRWYXIvck5LbEk0ODhKK29pN3pYOVUKxMKXjetwknNPo45Sj9bLs95jxR1MIayS
            572rbMvB58e9jIPCgmMMQFVlv/lqKNHjbZxMyJUNTGnUFgsEFar+XA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-20T01:12:43Z"
    mac: ENC[AES256_GCM,data:N15+CRrRZjbJnIU7smkctR6FHD2stY+wko+iuJARFBFc11fJM0UHwIvFerEADMbalIbdJYie/1h5ye673GRqg6+MTJlkXlv/NBcFTpm6/CjZh8Gk2kGaUe+GB4vTQL/DOM1gCeuTDu1UuYPuZYueOrtpAwm4Et9XTE1KR3xWjkg=,iv:v7fFFC3efn3Gs1mEhcrCfAHRqAz9+l25jS3g927ENAg=,tag:PcRY/trpHguBtVZl3u+d7Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
